import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/contexts/SessionContext";
import { DarkModeToggle } from "@/components/dark-mode-toggle";
import { Toaster } from "sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <SessionProvider>
                    <div className="w-full flex justify-end p-4 fixed top-0 left-0 z-50 pointer-events-none">
                        <div className="pointer-events-auto">
                            <DarkModeToggle />
                        </div>
                    </div>
                    <main>{children}</main>
                </SessionProvider>
                <Toaster />
            </body>
        </html>
    );
}
